const euroCountries = [
  { name: "Belgien", value: "BE" },
  { name: "Bulgarien", value: "BG" },
  { name: "Cypern", value: "CY" },
  { name: "Danmark", value: "DK" },
  { name: "Estland", value: "EE" },
  { name: "Finland", value: "FI" },
  { name: "Frankrike", value: "FR" },
  { name: "Grekland", value: "GR" },
  { name: "Irland", value: "IE" },
  { name: "Italien", value: "IT" },
  { name: "Lettland", value: "LV" },
  { name: "Liechtenstein", value: "LI" },
  { name: "Litauen", value: "LT" },
  { name: "Luxemberg", value: "LU" },
  { name: "Kroatien", value: "HR" },
  { name: "Malta", value: "MT" },
  { name: "Nederländerna", value: "NL" },
  { name: "Norge", value: "NO" },
  { name: "Polen", value: "PL" },
  { name: "Portugal", value: "PT" },
  { name: "Romänien", value: "RO" },
  { name: "Slovakien", value: "SK" },
  { name: "Slovenien", value: "SI" },
  { name: "Schweiz", value: "CH" },
  { name: "Spanien", value: "ES" },
  { name: "Sverige", value: "SE" },
  { name: "Storbritannien", value: "UK" },
  { name: "Tjeckien", value: "CZ" },
  { name: "Tyskland", value: "DE" },
  { name: "Ungern", value: "HU" },
  { name: "Österrike", value: "AT" },
];

export default euroCountries;
